import { Hono } from "hono";
import Layout from "./layout";
import Home from "./views/home";
import Blog from "./views/blog";
import RngoInit from "./views/blog/posts/release-friday/rngo-init";
import PlatformOverview from "./views/docs/platform/overview";
import SchemaOverview from "./views/docs/schema/overview";
import CliOverview from "./views/docs/cli/overview";
import QuickStart from "./views/docs/platform/guides/quick-start";
import Initialize from "./views/docs/platform/guides/initialize";
import Simulation from "./views/docs/platform/concepts/simulation";
import System from "./views/docs/platform/concepts/system";
import Effect from "./views/docs/platform/concepts/effect";
import Schema from "./views/docs/platform/concepts/schema";
import Array from "./views/docs/schema/primitive/array";
import Constant from "./views/docs/schema/primitive/constant";
import Context from "./views/docs/schema/primitive/context";
import Function from "./views/docs/schema/primitive/function";
import Number from "./views/docs/schema/primitive/number";
import Object from "./views/docs/schema/primitive/object";
import Reference from "./views/docs/schema/primitive/reference";
import Select from "./views/docs/schema/primitive/select";
import String from "./views/docs/schema/primitive/string";
import Run from "./views/docs/cli/run";
import Init from "./views/docs/cli/init";
import CustomSchemaTypes from "./views/blog/posts/release-friday/custom-schema-types";

const app = new Hono<{ Bindings: Env }>();

app.use(Layout);

app.get("/", (c) => c.render(<Home />));
app.get("/blog", (c) => c.render(<Blog />));
app.get("/blog/release-friday/rngo-init", (c) => c.render(<RngoInit />));
app.get("/blog/release-friday/custom-schema-types", (c) => c.render(<CustomSchemaTypes />));
app.get("/docs", (c) => c.render(<PlatformOverview />));
app.get("/docs/guides/quick-start", (c) => c.render(<QuickStart />));
app.get("/docs/guides/initialize", (c) => c.render(<Initialize />));
app.get("/docs/concepts/simulation", (c) => c.render(<Simulation />));
app.get("/docs/concepts/system", (c) => c.render(<System />));
app.get("/docs/concepts/effect", (c) => c.render(<Effect />));
app.get("/docs/concepts/schema", (c) => c.render(<Schema />));
app.get("/docs/schema", (c) => c.render(<SchemaOverview />));
app.get("/docs/schema/primitive/array", (c) => c.render(<Array />));
app.get("/docs/schema/primitive/constant", (c) => c.render(<Constant />));
app.get("/docs/schema/primitive/context", (c) => c.render(<Context />));
app.get("/docs/schema/primitive/function", (c) => c.render(<Function />));
app.get("/docs/schema/primitive/number", (c) => c.render(<Number />));
app.get("/docs/schema/primitive/object", (c) => c.render(<Object />));
app.get("/docs/schema/primitive/reference", (c) => c.render(<Reference />));
app.get("/docs/schema/primitive/select", (c) => c.render(<Select />));
app.get("/docs/schema/primitive/string", (c) => c.render(<String />));
app.get("/docs/cli", (c) => c.render(<CliOverview />));
app.get("/docs/cli/init", (c) => c.render(<Init />));
app.get("/docs/cli/run", (c) => c.render(<Run />));

export default app;
